// ============================================================
// 关卡数据 · 第一章「新手村」（5 关，含 Boss 关）
// 判定类型：
//   command : 匹配用户输入的命令行（正则）
//   file    : 命令匹配(alsoCommand) + 沙箱文件状态确认(path/contains/nonEmpty)
//   output  : 命令匹配(alsoCommand) + 终端输出确认(pattern；dynamicOutput=true 时按输入动态核对)
// teach    : 教学卡片 —— 先教后练
// setupCmds : 关卡开始时在沙箱内自动执行的初始化命令
// ============================================================

export const CHAPTERS = [
  {
    id: 1,
    emoji: "🏕️",
    name: "新手村",
    subtitle: "终端基础 · 学会与 Linux 对话",
    blurb: "这里是所有冒险者的起点。学会用命令与这个世界对话，就能走出新手村。",
  },
  {
    id: 2,
    emoji: "🌀",
    name: "文件迷宫",
    subtitle: "文件系统 · 在目录与文件间穿梭",
    blurb: "迷宫由目录和文件构成。学会 cd / mkdir / cp / mv / rm / find，你就能在其中来去自如。",
  },
  {
    id: 3,
    emoji: "🏰",
    name: "权限要塞",
    subtitle: "用户与权限 · 守护你的领地",
    blurb: "要塞由权限守护。学会 ls -l / chmod / chown / adduser，你就能掌控谁能进入、谁能修改。",
  },
];

/** 所有关卡共用的错误模式（放在关卡 errorPatterns 之后） */
export const COMMON_ERRORS = [
  { pattern: "^[^\\x00-\\x7f]", message: "🤖 命令要用英文哦（echo 后面的内容可以写中文，例如 echo 你好）" },
];

export const LEVELS = [
  {
    id: "1-1",
    chapter: 1,
    icon: "🌱",
    title: "你好，世界",
    subtitle: "运行你的第一条命令",
    timeLimit: null,
    xp: 50,
    coins: 20,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 4 } },
    story: [
      "你睁开眼睛，发现自己站在一块发着微光的屏幕前。",
      "一只小企鹅蹦了出来：「冒险者你好！我是 Tux，你的向导。」",
      "「来，先跟这个世界打个招呼吧——我会一步步教你，学会了再动手！」",
    ],
    setupCmds: ["cd /"],
    errorPatterns: [
      { pattern: "^echo( |$)", message: "echo 后面要跟上想说的话哦，例如：echo 你好" },
      { pattern: "^sl( |$)", message: "🐎 马儿跑反了！sl 是火车彩蛋。这里试试 echo：echo 你好" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 echo 说一句「你好」",
        judge: { type: "output", alsoCommand: "^echo\\s+\\S", dynamicOutput: true },
        teach: {
          cmd: "echo",
          cmdZh: "回声",
          what: "把跟在后面的文字原样打印到屏幕上，就像山谷里的回声。",
          syntax: "echo 文字",
          example: "echo 你好，世界",
          exampleOut: "你好，世界",
          tip: "echo 是最常用的输出命令，写脚本时天天见。注意：echo 后面必须跟上要说的内容。",
        },
        hints: [
          "echo 是「回声」命令，会把你说的话原样打印出来（后面必须跟内容）",
          "试试：echo hello",
          "在终端输入：echo hello 然后回车",
        ],
      },
      {
        id: "t2",
        desc: "用 date 看看现在几点",
        judge: { type: "output", alsoCommand: "^date( |$)", pattern: "[A-Z][a-z]{2} [A-Z][a-z]{2} +[0-9]{1,2}" },
        teach: {
          cmd: "date",
          cmdZh: "日期时间",
          what: "显示系统当前的日期和时间。",
          syntax: "date",
          example: "date",
          exampleOut: "Fri Sep 25 12:00:00 UTC 2026",
          tip: "想自定义格式？试试 date +%Y-%m-%d",
        },
        hints: [
          "date 会显示系统当前时间",
          "直接输入 date 回车即可",
          "在终端输入：date",
        ],
      },
      {
        id: "t3",
        desc: "用 clear 清空屏幕，准备出发",
        judge: { type: "output", alsoCommand: "^clear( |$)", pattern: "\\x1b\\[H" },
        teach: {
          cmd: "clear",
          cmdZh: "清屏",
          what: "清空终端屏幕上的所有内容，让眼前干干净净。",
          syntax: "clear",
          example: "clear",
          exampleOut: "（屏幕变空白）",
          tip: "⚠️ 屏幕突然变空白是正常现象，不是 bug！任务面板和提示都不受影响。",
        },
        hints: [
          "clear 是清屏命令，让屏幕干净如新",
          "输入 clear 回车",
          "在终端输入：clear",
        ],
      },
    ],
  },
  {
    id: "1-2",
    chapter: 1,
    icon: "🪪",
    title: "我是谁",
    subtitle: "认识自己与所在的位置",
    timeLimit: null,
    xp: 50,
    coins: 20,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 4 } },
    story: [
      "村长笑眯眯地拦住你：「新来的冒险者，登记一下你的信息吧。」",
      "Tux 凑过来小声说：「三个命令就能完成登记——先看看自己是谁。」",
    ],
    setupCmds: ["cd /"],
    errorPatterns: [
      { pattern: "^who( |$)", message: "差一点！这个命令是 whoami，三个单词连在一起写" },
      { pattern: "^pws( |$)|^pwdw( |$)", message: "拼写检查：显示当前路径的命令是 pwd" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 whoami 看看「我是谁」",
        judge: { type: "output", alsoCommand: "^whoami( |$)", pattern: "root" },
        teach: {
          cmd: "whoami",
          cmdZh: "我是谁",
          what: "打印当前登录的用户名。",
          syntax: "whoami",
          example: "whoami",
          exampleOut: "root",
          tip: "who am i 的缩写，记得连在一起写。",
        },
        hints: [
          "whoami = who am i（我是谁），会打印当前用户名",
          "输入 whoami 回车，看它回答什么",
          "在终端输入：whoami",
        ],
      },
      {
        id: "t2",
        desc: "用 pwd 看看「我在哪」",
        judge: { type: "output", alsoCommand: "^pwd( |$)", pattern: "^/" },
        teach: {
          cmd: "pwd",
          cmdZh: "我在哪",
          what: "打印当前所在目录的完整路径。",
          syntax: "pwd",
          example: "pwd",
          exampleOut: "/",
          tip: "print working directory 的缩写，迷路时就敲它。",
        },
        hints: [
          "pwd = print working directory（打印当前目录）",
          "输入 pwd 回车，它会告诉你当前所在路径",
          "在终端输入：pwd",
        ],
      },
      {
        id: "t3",
        desc: "用 hostname 问问这台机器叫什么名字",
        judge: { type: "output", alsoCommand: "^hostname( |$)", pattern: "^hostname\\n.*\\n" },
        teach: {
          cmd: "hostname",
          cmdZh: "主机名",
          what: "显示这台电脑的名字（主机名）。",
          syntax: "hostname",
          example: "hostname",
          exampleOut: "(none)",
          tip: "这台迷你机器还没起名，所以显示 (none)。试试 hostname 新名字 给它命名（进阶玩法）！",
        },
        hints: [
          "hostname 会打印这台电脑的主机名",
          "输入 hostname 回车",
          "在终端输入：hostname",
        ],
      },
    ],
  },
  {
    id: "1-3",
    chapter: 1,
    icon: "📦",
    title: "环顾四周",
    subtitle: "用 ls 清点仓库物资",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 5 } },
    story: [
      "村长带你去仓库：「商队送来的货物堆在这里，帮我清点一下。」",
      "「听说仓库里还藏着一件『看不见的宝物』——传说中能带来好运的龙之金币，只有细心的人才能找到。」",
    ],
    setupCmds: [
      "cd /",
      "mkdir -p /mnt/adv/warehouse",
      "cd /mnt/adv/warehouse",
      "touch apple.txt bread.txt milk.txt",
      "echo 'TREASURE! 龙之金币：你找到了隐藏的宝藏。' > .treasure",
    ],
    errorPatterns: [
      { pattern: "^ls-a( |$)", message: "命令和选项之间要有空格：ls -a" },
      { pattern: "^la( |$)", message: "字母顺序反了：是 ls，不是 la" },
      { pattern: "^cat\\.treasure( |$)", message: "cat 和 .treasure 之间要有空格：cat .treasure" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 ls 列出当前目录",
        judge: { type: "output", alsoCommand: "^ls( |$)", pattern: "apple\\.txt" },
        teach: {
          cmd: "ls",
          cmdZh: "列出目录",
          what: "列出当前目录下的文件和文件夹。",
          syntax: "ls",
          example: "ls",
          exampleOut: "apple.txt  bread.txt  milk.txt",
          tip: "list 的缩写，是使用频率最高的命令之一。",
        },
        hints: [
          "ls = list，列出当前目录下的文件和文件夹",
          "输入 ls 回车",
          "在终端输入：ls",
        ],
      },
      {
        id: "t2",
        desc: "用 ls -l 查看货物详情",
        judge: { type: "output", alsoCommand: "^ls .*-l", pattern: "-rw-r--r--.*apple\\.txt" },
        teach: {
          cmd: "ls -l",
          cmdZh: "长格式",
          what: "-l 是「长格式」选项，能看到大小、时间、权限等详细信息。",
          syntax: "ls -l",
          example: "ls -l",
          exampleOut: "-rw-r--r-- 1 root root 0 Sep 25 12:00 apple.txt",
          tip: "- 开头的是文件，d 开头的是目录（后面章节会细讲权限）。",
        },
        hints: [
          "-l 是「长格式」，能看到大小、时间等详细信息",
          "试试：ls -l",
          "在终端输入：ls -l",
        ],
      },
      {
        id: "t3",
        desc: "用 ls -a 找出「看不见的宝物」",
        judge: { type: "output", alsoCommand: "^ls .*-a", pattern: "\\.treasure" },
        teach: {
          cmd: "ls -a",
          cmdZh: "显示全部",
          what: "-a（all）让隐藏文件也现形——Linux 里以 . 开头的文件都是隐藏的。",
          syntax: "ls -a",
          example: "ls -a",
          exampleOut: ".  ..  .treasure  apple.txt  bread.txt  milk.txt",
          tip: "隐藏不是加密，只是「默认不显示」，ls -a 就能看见。",
        },
        hints: [
          "-a = all，连隐藏文件（以 . 开头的）也显示出来",
          "试试：ls -a",
          "在终端输入：ls -a",
        ],
      },
      {
        id: "t4",
        desc: "用 cat 打开宝物文件 .treasure（文件名以点开头）",
        judge: { type: "output", alsoCommand: "^cat +\\.treasure( |$)", pattern: "TREASURE!" },
        teach: {
          cmd: "cat",
          cmdZh: "查看文件",
          what: "把文件内容打印到屏幕上。宝物（龙之金币）就藏在隐藏文件 .treasure 里——就是 ls -a 输出里那个以点开头的文件。",
          syntax: "cat 文件名",
          example: "cat .treasure",
          exampleOut: "TREASURE! 龙之金币：你找到了隐藏的宝藏。",
          tip: "开头的点是文件名的一部分：.treasure 念作「点 treasure」。cat 是 concatenate（连接）的缩写，一次可以看多个文件。",
        },
        hints: [
          "宝物藏在一个隐藏文件里，文件名是 .treasure（点开头 = 隐藏文件）",
          "试试：cat .treasure",
          "在终端输入：cat .treasure 然后回车",
        ],
      },
    ],
  },
  {
    id: "1-4",
    chapter: 1,
    icon: "🗺️",
    title: "地图与罗盘",
    subtitle: "学会自己查阅命令手册",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 6 }, three: { maxSteps: 4 } },
    story: [
      "Tux 摊开爪子：「冒险者不能永远靠向导。每个命令都自带说明书，学会自己查！」",
      "「用 --help 选项，命令就会告诉你它怎么用。」",
    ],
    setupCmds: ["cd /"],
    errorPatterns: [
      { pattern: "^man( |$)", message: "这个迷你世界没有 man 手册，试试 <命令> --help（例如 ls --help）" },
      { pattern: "^help( |$)", message: "试试 <命令> --help，例如 date --help" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 ls --help 查看 ls 的说明书",
        judge: { type: "output", alsoCommand: "^ls +--help", pattern: "Usage|usage" },
        teach: {
          cmd: "ls --help",
          cmdZh: "命令说明书",
          what: "在命令后加 --help，它就会打印自己的使用说明——这是自学 Linux 的万能钥匙。",
          syntax: "命令 --help",
          example: "ls --help",
          exampleOut: "Usage: ls [-1AaCxdLHRFplinsehrsXvctu]...",
          tip: "几乎所有命令都支持 --help，比翻书快多了。",
        },
        hints: [
          "在命令后加 --help 就能看到它的用法说明",
          "试试：ls --help",
          "在终端输入：ls --help",
        ],
      },
      {
        id: "t2",
        desc: "用 date --help 查看 date 的说明书",
        judge: { type: "output", alsoCommand: "^date +--help", pattern: "Usage|usage" },
        teach: {
          cmd: "date --help",
          cmdZh: "举一反三",
          what: "同样的方法适用于任何命令——换成 date 试试。",
          syntax: "date --help",
          example: "date --help",
          exampleOut: "Usage: date [OPTIONS]...",
          tip: "学会 --help，你就拿到了所有命令的说明书。",
        },
        hints: [
          "同样的方法适用于任何命令",
          "试试：date --help",
          "在终端输入：date --help",
        ],
      },
      {
        id: "t3",
        desc: "用 history 回顾你敲过的命令",
        judge: { type: "output", alsoCommand: "^history( |$)", pattern: "^history\\n +[0-9]" },
        teach: {
          cmd: "history",
          cmdZh: "命令历史",
          what: "列出你在这个终端里敲过的所有命令。",
          syntax: "history",
          example: "history",
          exampleOut: "1 echo hello\n2 date\n3 ls --help\n...",
          tip: "按键盘的 ↑ 方向键也能翻出之前的命令。",
        },
        hints: [
          "history 会列出你在这个终端里敲过的所有命令",
          "输入 history 回车",
          "在终端输入：history",
        ],
      },
    ],
  },
  {
    id: "1-5",
    chapter: 1,
    icon: "⚔️",
    title: "新手试炼（Boss）",
    subtitle: "限时综合挑战 · 建立你的营地",
    timeLimit: 300,
    xp: 150,
    coins: 60,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 6 } },
    story: [
      "村长击鼓三声：「新手试炼开始！在 5 分钟内，建立属于你的营地！」",
      "任务：创建营地 → 制作战旗 → 写下宣言 → 检阅你的成果。",
      "Tux 大喊：「别慌，每个任务开始前都有教学卡片，计时也会暂停——用你学过的命令，一步一个脚印！」",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv", "cd /mnt/adv"],
    errorPatterns: [
      { pattern: "^echo( |$)", message: "echo 后面要有内容再重定向：echo 冲啊 > camp/flag.txt" },
      { pattern: "^mkdr( |$)", message: "mkdir 少了个 i：mkdir camp" },
      { pattern: "^tuch( |$)", message: "拼写检查：是 touch，不是 tuch" },
      { pattern: "^touch +flag\\.txt( |$)", message: "战旗要放进营地目录 camp 里：touch camp/flag.txt" },
      { pattern: "^touch +camp( |$)", message: "touch 后面要跟文件名：touch camp/flag.txt" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 mkdir 创建营地目录 camp",
        judge: { type: "command", pattern: "^mkdir +camp( |$)" },
        teach: {
          cmd: "mkdir",
          cmdZh: "创建目录",
          what: "创建新的文件夹（目录）。",
          syntax: "mkdir 目录名",
          example: "mkdir camp",
          exampleOut: "（无输出，表示成功）",
          tip: "make directory 的缩写。Linux 哲学：没有消息就是好消息。",
        },
        hints: [
          "mkdir = make directory（创建目录）",
          "试试：mkdir camp",
          "在终端输入：mkdir camp",
        ],
      },
      {
        id: "t2",
        desc: "用 touch 制作战旗 camp/flag.txt",
        judge: { type: "file", path: "adv/camp/flag.txt", alsoCommand: "^touch +camp/flag\\.txt( |$)" },
        teach: {
          cmd: "touch",
          cmdZh: "创建文件",
          what: "创建一个空文件；如果文件已存在，就更新它的修改时间。",
          syntax: "touch 文件名",
          example: "touch camp/flag.txt",
          exampleOut: "（无输出，表示成功）",
          tip: "camp/flag.txt 表示「camp 目录里的 flag.txt」。",
        },
        hints: [
          "touch 可以创建一个空文件；camp/flag.txt 表示营地里的文件",
          "试试：touch camp/flag.txt",
          "在终端输入：touch camp/flag.txt",
        ],
      },
      {
        id: "t3",
        desc: "在战旗上写下你的宣言（echo ... > camp/flag.txt）",
        judge: { type: "file", path: "adv/camp/flag.txt", nonEmpty: true, alsoCommand: "^echo\\s+.+> *camp/flag\\.txt( |$)" },
        teach: {
          cmd: "> 重定向",
          cmdZh: "写入文件",
          what: "> 是「重定向」：把命令的输出写进文件，而不是打印到屏幕。",
          syntax: "echo 文字 > 文件",
          example: "echo 冲啊 > camp/flag.txt",
          exampleOut: "（无输出，内容被写进了文件）",
          tip: "> 会覆盖原文件内容；>> 则是追加到文件末尾。宣言不能是空的哦。",
        },
        hints: [
          "> 是「重定向」：把 echo 的输出写进文件而不是屏幕",
          "试试：echo 冲啊 > camp/flag.txt",
          "在终端输入：echo 冲啊 > camp/flag.txt",
        ],
      },
      {
        id: "t4",
        desc: "用 cat 打开战旗文件 camp/flag.txt",
        judge: { type: "output", alsoCommand: "^cat +camp/flag\\.txt( |$)", pattern: "^cat +camp/flag\\.txt\\n.+\\n" },
        teach: {
          cmd: "cat",
          cmdZh: "查看文件",
          what: "把文件内容打印到屏幕上——打开 camp/flag.txt，看看你的宣言写进去没有。",
          syntax: "cat 文件名",
          example: "cat camp/flag.txt",
          exampleOut: "冲啊",
          tip: "写文件之后用 cat 验证，是运维的肌肉记忆。",
        },
        hints: [
          "cat 用来查看文件内容",
          "试试：cat camp/flag.txt",
          "在终端输入：cat camp/flag.txt",
        ],
      },
      {
        id: "t5",
        desc: "用 ls -l camp 检阅营地",
        judge: { type: "output", alsoCommand: "^ls .*camp.*-l|^ls .*-l.*camp", pattern: "flag\\.txt" },
        teach: {
          cmd: "ls -l 目录",
          cmdZh: "检阅目录",
          what: "长格式查看指定目录下的文件详情。",
          syntax: "ls -l 目录名",
          example: "ls -l camp",
          exampleOut: "-rw-r--r-- 1 root root 7 Sep 25 12:00 flag.txt",
          tip: "看 flag.txt 的大小——「冲啊」加换行正好是 7 个字节（UTF-8）。",
        },
        hints: [
          "组合使用：ls -l 加目录名",
          "试试：ls -l camp",
          "在终端输入：ls -l camp",
        ],
      },
    ],
  },
  {
    id: "2-1",
    chapter: 2,
    icon: "🚪",
    title: "走进迷宫",
    subtitle: "用 cd 在目录间穿梭",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 5 } },
    story: [
      "你来到一座巨大的文件迷宫，大厅里有两个房间：room-a 和 room-b。",
      "Tux 说：「用 cd 命令就能在迷宫里移动——先学会相对路径和绝对路径。」",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/maze/room-a /mnt/adv/maze/room-b", "cd /mnt/adv/maze", "touch entrance.txt"],
    errorPatterns: [
      { pattern: "^cd( |$)", message: "cd 后面要跟目的地，例如：cd room-a" },
      { pattern: "^cd +\\.( |$)", message: "cd . 是原地不动哦，试试 cd .. 退回上一级" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 cd room-a 进入房间 A（相对路径）",
        judge: { type: "command", pattern: "^cd +room-a( |$)" },
        teach: {
          cmd: "cd room-a",
          cmdZh: "相对路径",
          what: "cd 是 change directory（切换目录）。直接写目录名就是相对路径——相对当前位置找路。",
          syntax: "cd 目录名",
          example: "cd room-a",
          exampleOut: "（没有输出 = 成功，提示符会变化）",
          tip: "相对路径从「当前所在位置」出发；绝对路径从根 / 出发，例如 cd /mnt/adv/maze/room-a",
        },
        hints: [
          "cd = change directory（切换目录）",
          "试试：cd room-a",
          "在终端输入：cd room-a",
        ],
      },
      {
        id: "t2",
        desc: "用 cd .. 退回迷宫大厅",
        judge: { type: "command", pattern: "^cd +\\.\\.( |$)" },
        teach: {
          cmd: "cd ..",
          cmdZh: "上一级目录",
          what: ".. 代表上一级目录（父目录）。cd .. 就是「往回走一层」。",
          syntax: "cd ..",
          example: "cd ..",
          exampleOut: "（没有输出 = 成功）",
          tip: ". 代表当前目录，.. 代表上一级——这是每个目录都有的两个隐藏入口。",
        },
        hints: [
          ".. 代表上一级目录",
          "试试：cd ..",
          "在终端输入：cd ..",
        ],
      },
      {
        id: "t3",
        desc: "用 cd /mnt/adv/maze/room-b 进入房间 B（绝对路径）",
        judge: { type: "command", pattern: "^cd +/mnt/adv/maze/room-b( |$)" },
        teach: {
          cmd: "cd /mnt/adv/maze/room-b",
          cmdZh: "绝对路径",
          what: "绝对路径以 / 开头，从根目录一路写到目的地——不管你在哪，都能直达。",
          syntax: "cd /完整/路径",
          example: "cd /mnt/adv/maze/room-b",
          exampleOut: "（没有输出 = 成功）",
          tip: "路径像地址：相对路径是「往前两条街左转」，绝对路径是「XX市XX区XX路1号」。",
        },
        hints: [
          "绝对路径以 / 开头，写完整路径",
          "试试：cd /mnt/adv/maze/room-b",
          "在终端输入：cd /mnt/adv/maze/room-b",
        ],
      },
      {
        id: "t4",
        desc: "用 pwd 确认你到了房间 B",
        judge: { type: "output", alsoCommand: "^pwd( |$)", pattern: "/mnt/adv/maze/room-b" },
        teach: {
          cmd: "pwd",
          cmdZh: "确认位置",
          what: "pwd 打印当前所在目录的完整路径——迷路时的指南针。",
          syntax: "pwd",
          example: "pwd",
          exampleOut: "/mnt/adv/maze/room-b",
          tip: "只要 pwd 显示 room-b，就说明前面三步 cd 全部走对了。",
        },
        hints: [
          "pwd 会显示你当前所在路径",
          "输入 pwd 回车",
          "在终端输入：pwd",
        ],
      },
    ],
  },
  {
    id: "2-2",
    chapter: 2,
    icon: "🧱",
    title: "创造与毁灭",
    subtitle: "mkdir / touch / rmdir / rm",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 5 } },
    story: [
      "空地上堆着旧棚屋 old_hut 和过时的图纸 old_plans.txt。",
      "Tux 递给你工具：「建起你的工坊 workshop，再清理掉没用的旧物。」",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/build", "cd /mnt/adv/build", "mkdir old_hut", "touch old_plans.txt", "touch stone.txt"],
    errorPatterns: [
      { pattern: "^rmdir +workshop( |$)", message: "workshop 不是空目录，rmdir 只能删空目录" },
      { pattern: "^rm +workshop( |$)", message: "删目录要用 rm -r，这关只需要删文件 old_plans.txt" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 mkdir 创建工坊目录 workshop",
        judge: { type: "file", path: "adv/build/workshop", alsoCommand: "^mkdir +workshop( |$)" },
        teach: {
          cmd: "mkdir",
          cmdZh: "创建目录",
          what: "mkdir（make directory）创建新目录。",
          syntax: "mkdir 目录名",
          example: "mkdir workshop",
          exampleOut: "（没有输出 = 成功）",
          tip: "mkdir -p 可以一次创建多层目录：mkdir -p a/b/c",
        },
        hints: [
          "mkdir = make directory（创建目录）",
          "试试：mkdir workshop",
          "在终端输入：mkdir workshop",
        ],
      },
      {
        id: "t2",
        desc: "用 touch 在工坊里放一张图纸 plan.txt",
        judge: { type: "file", path: "adv/build/workshop/plan.txt", alsoCommand: "^touch +workshop/plan\\.txt( |$)" },
        teach: {
          cmd: "touch",
          cmdZh: "创建文件",
          what: "touch 创建空文件；文件已存在时则更新它的修改时间。",
          syntax: "touch 文件名",
          example: "touch workshop/plan.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "workshop/plan.txt 表示「workshop 目录里的 plan.txt」。",
        },
        hints: [
          "touch 创建空文件；写在 workshop 目录里",
          "试试：touch workshop/plan.txt",
          "在终端输入：touch workshop/plan.txt",
        ],
      },
      {
        id: "t3",
        desc: "用 rmdir 拆除空棚屋 old_hut",
        judge: { type: "file", path: "adv/build/old_hut", absent: true, alsoCommand: "^rmdir +old_hut( |$)" },
        teach: {
          cmd: "rmdir",
          cmdZh: "删除空目录",
          what: "rmdir（remove directory）删除目录——只能删空的目录。",
          syntax: "rmdir 目录名",
          example: "rmdir old_hut",
          exampleOut: "（没有输出 = 成功）",
          tip: "目录里有东西时 rmdir 会拒绝删除，这是 Linux 的保护机制。",
        },
        hints: [
          "rmdir = remove directory（删除目录）",
          "试试：rmdir old_hut",
          "在终端输入：rmdir old_hut",
        ],
      },
      {
        id: "t4",
        desc: "用 rm 销毁旧图纸 old_plans.txt",
        judge: { type: "file", path: "adv/build/old_plans.txt", absent: true, alsoCommand: "^rm +old_plans\\.txt( |$)" },
        teach: {
          cmd: "rm",
          cmdZh: "删除文件",
          what: "rm（remove）删除文件，删掉就找不回来了。",
          syntax: "rm 文件名",
          example: "rm old_plans.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "⚠️ rm 没有回收站！删除前一定要看清楚文件名。",
        },
        hints: [
          "rm = remove（删除文件）",
          "试试：rm old_plans.txt",
          "在终端输入：rm old_plans.txt",
        ],
      },
    ],
  },
  {
    id: "2-3",
    chapter: 2,
    icon: "📦",
    title: "搬运与复制",
    subtitle: "cp / mv / cp -r",
    timeLimit: null,
    xp: 70,
    coins: 30,
    starRules: { two: { maxSteps: 9 }, three: { maxSteps: 6 } },
    story: [
      "商队留下一批物资：藏宝图 map.txt、工具包 tools、还有块石头 stone.txt。",
      "Tux 说：「把藏宝图复制一份、工具包备份一份、石头改个名字——用 cp 和 mv。」",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/move/tools", "cd /mnt/adv/move", "echo 'X marks the spot' > map.txt", "touch tools/axe.txt", "touch stone.txt"],
    errorPatterns: [
      { pattern: "^cp +tools +tools_bak( |$)", message: "复制目录要加 -r（递归）：cp -r tools tools_bak" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 cp 复制藏宝图 map.txt → map_copy.txt",
        judge: { type: "file", path: "adv/move/map_copy.txt", contains: "X marks the spot", alsoCommand: "^cp +map\\.txt +map_copy\\.txt( |$)" },
        teach: {
          cmd: "cp",
          cmdZh: "复制文件",
          what: "cp（copy）复制文件：cp 源文件 目标文件。",
          syntax: "cp 源文件 新文件",
          example: "cp map.txt map_copy.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "复制后两个文件内容完全一样，改其中一个不影响另一个。",
        },
        hints: [
          "cp = copy：cp 源文件 目标文件",
          "试试：cp map.txt map_copy.txt",
          "在终端输入：cp map.txt map_copy.txt",
        ],
      },
      {
        id: "t2",
        desc: "用 mv 把复制品搬进工具包 mv map_copy.txt tools/",
        judge: { type: "file", path: "adv/move/tools/map_copy.txt", alsoCommand: "^mv +map_copy\\.txt +tools/?( |$)" },
        teach: {
          cmd: "mv",
          cmdZh: "移动/改名",
          what: "mv（move）把文件移动（或改名）：mv 源 目标。目标写成目录名就是搬进去。",
          syntax: "mv 文件 目录/",
          example: "mv map_copy.txt tools/",
          exampleOut: "（没有输出 = 成功）",
          tip: "mv 到「目录/」表示搬进该目录；mv a b 则把 a 改名为 b。",
        },
        hints: [
          "mv = move：mv 文件 目标目录",
          "试试：mv map_copy.txt tools/",
          "在终端输入：mv map_copy.txt tools/",
        ],
      },
      {
        id: "t3",
        desc: "用 cp -r 备份整个工具包 → tools_bak",
        judge: { type: "file", path: "adv/move/tools_bak/axe.txt", alsoCommand: "^cp +-r +tools +tools_bak( |$)" },
        teach: {
          cmd: "cp -r",
          cmdZh: "复制目录",
          what: "复制目录必须加 -r（recursive 递归），把整个目录连内容一起复制。",
          syntax: "cp -r 目录 新目录",
          example: "cp -r tools tools_bak",
          exampleOut: "（没有输出 = 成功）",
          tip: "不加 -r 复制目录会报错，这是最常见的 cp 坑。",
        },
        hints: [
          "复制目录要加 -r 选项",
          "试试：cp -r tools tools_bak",
          "在终端输入：cp -r tools tools_bak",
        ],
      },
      {
        id: "t4",
        desc: "用 mv 给石头改名 stone.txt → rock.txt",
        judge: { type: "file", path: "adv/move/rock.txt", alsoCommand: "^mv +stone\\.txt +rock\\.txt( |$)" },
        teach: {
          cmd: "mv 改名",
          cmdZh: "文件改名",
          what: "mv 的第二个用法：源和目标都是文件名时，就是改名。",
          syntax: "mv 旧名 新名",
          example: "mv stone.txt rock.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "Linux 没有单独的 rename 命令，改名都用 mv。",
        },
        hints: [
          "mv 旧名字 新名字 = 改名",
          "试试：mv stone.txt rock.txt",
          "在终端输入：mv stone.txt rock.txt",
        ],
      },
    ],
  },
  {
    id: "2-4",
    chapter: 2,
    icon: "🔦",
    title: "迷雾中的宝藏",
    subtitle: "通配符 * 与 find",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 5 } },
    story: [
      "浓雾笼罩着藏宝地，宝物 gold.txt 藏在某个角落，周围还有 silver、bronze 和 ghost 文件干扰视线。",
      "Tux 压低声音：「先学通配符 *，再用 find 精准搜索。」",
    ],
    setupCmds: [
      "cd /",
      "mkdir -p /mnt/adv/fog/north",
      "mkdir -p /mnt/adv/fog/east",
      "mkdir -p /mnt/adv/fog/south",
      "cd /mnt/adv/fog",
      "touch north/gold.txt north/silver.txt east/bronze.txt south/ghost.txt",
      "touch root1.txt root2.txt",
      "echo 'GOLD! The treasure is yours.' > north/gold.txt",
    ],
    errorPatterns: [],
    tasks: [
      {
        id: "t1",
        desc: "用 ls *.txt 列出当前目录所有 txt 文件（通配符 *）",
        judge: { type: "output", alsoCommand: "^ls +\\*\\.txt( |$)", pattern: "root1\\.txt" },
        teach: {
          cmd: "ls *.txt",
          cmdZh: "通配符 *",
          what: "* 是通配符，代表任意多个字符。*.txt 就表示「所有以 .txt 结尾的文件」。",
          syntax: "ls *.txt",
          example: "ls *.txt",
          exampleOut: "root1.txt  root2.txt",
          tip: "* 由 shell 展开成真实文件名后再交给命令，所以 ls 看到的是完整列表。",
        },
        hints: [
          "* 代表任意字符，*.txt = 所有 txt 文件",
          "试试：ls *.txt",
          "在终端输入：ls *.txt",
        ],
      },
      {
        id: "t2",
        desc: "用 ls north/*.txt 看看北边有哪些 txt",
        judge: { type: "output", alsoCommand: "^ls +north/\\*\\.txt( |$)", pattern: "silver" },
        teach: {
          cmd: "ls north/*.txt",
          cmdZh: "目录+通配符",
          what: "通配符可以带路径：north/*.txt 表示 north 目录下的所有 txt 文件。",
          syntax: "ls 目录/*.txt",
          example: "ls north/*.txt",
          exampleOut: "north/gold.txt  north/silver.txt",
          tip: "路径和通配符组合，就能在大迷宫里批量定位文件。",
        },
        hints: [
          "在目录名后接 /*.txt",
          "试试：ls north/*.txt",
          "在终端输入：ls north/*.txt",
        ],
      },
      {
        id: "t3",
        desc: "用 find . -name gold.txt 全迷宫搜索宝物",
        judge: { type: "output", alsoCommand: "^find +\\. +-name +gold\\.txt( |$)", pattern: "north/gold" },
        teach: {
          cmd: "find",
          cmdZh: "搜索文件",
          what: "find 从指定位置出发递归搜索：find 起点 -name 文件名。",
          syntax: "find . -name 文件名",
          example: "find . -name gold.txt",
          exampleOut: "./north/gold.txt",
          tip: "find 会钻进每一层子目录，是迷雾里最可靠的探照灯。",
        },
        hints: [
          "find 起点 -name 文件名（. 代表当前目录）",
          "试试：find . -name gold.txt",
          "在终端输入：find . -name gold.txt",
        ],
      },
      {
        id: "t4",
        desc: "用 cat north/gold.txt 打开宝物",
        judge: { type: "output", alsoCommand: "^cat +north/gold\\.txt( |$)", pattern: "GOLD!" },
        teach: {
          cmd: "cat 路径",
          cmdZh: "打开宝物",
          what: "按 find 给出的路径，用 cat 打开宝物文件。",
          syntax: "cat 路径/文件名",
          example: "cat north/gold.txt",
          exampleOut: "GOLD! The treasure is yours.",
          tip: "find 找到路径 → cat 打开内容，这就是搜索的标准流程。",
        },
        hints: [
          "find 告诉你路径是 ./north/gold.txt",
          "试试：cat north/gold.txt",
          "在终端输入：cat north/gold.txt",
        ],
      },
    ],
  },
  {
    id: "2-5",
    chapter: 2,
    icon: "📜",
    title: "阅读卷轴",
    subtitle: "head / tail / wc 分段阅读",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 8 }, three: { maxSteps: 5 } },
    story: [
      "长老递给你一卷 20 行的上古卷轴 scroll.txt：「全看太慢，学会分段阅读。」",
      "Tux 补充：「head 看开头、tail 看结尾、wc 数行数——三件套。」",
    ],
    setupCmds: [
      "cd /",
      "mkdir -p /mnt/adv/scrolls",
      "cd /mnt/adv/scrolls",
      "for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do echo line$i >> scroll.txt; done",
    ],
    errorPatterns: [
      { pattern: "^more +( |$)|^less +( |$)", message: "这个迷你世界没有 less/more，试试 head 或 tail" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 head -3 scroll.txt 看卷轴开头 3 行",
        judge: { type: "output", alsoCommand: "^head +-3 +scroll\\.txt( |$)", pattern: "^head +-3 +scroll\\.txt\\nline1\\nline2\\nline3" },
        teach: {
          cmd: "head -3",
          cmdZh: "看开头",
          what: "head 默认显示文件前 10 行，加 -3 只看前 3 行。",
          syntax: "head -行数 文件名",
          example: "head -3 scroll.txt",
          exampleOut: "line1\nline2\nline3",
          tip: "大文件先 head 看开头，是最省时的习惯。",
        },
        hints: [
          "head = 看开头；-3 表示只看 3 行",
          "试试：head -3 scroll.txt",
          "在终端输入：head -3 scroll.txt",
        ],
      },
      {
        id: "t2",
        desc: "用 tail -3 scroll.txt 看卷轴结尾 3 行",
        judge: { type: "output", alsoCommand: "^tail +-3 +scroll\\.txt( |$)", pattern: "^tail +-3 +scroll\\.txt\\nline18\\nline19\\nline20" },
        teach: {
          cmd: "tail -3",
          cmdZh: "看结尾",
          what: "tail 默认显示最后 10 行，加 -3 只看最后 3 行。",
          syntax: "tail -行数 文件名",
          example: "tail -3 scroll.txt",
          exampleOut: "line18\nline19\nline20",
          tip: "日志文件天天都在增长，运维最爱 tail 看最新记录。",
        },
        hints: [
          "tail = 看结尾；-3 表示只看 3 行",
          "试试：tail -3 scroll.txt",
          "在终端输入：tail -3 scroll.txt",
        ],
      },
      {
        id: "t3",
        desc: "用 wc -l scroll.txt 数数卷轴有多少行",
        judge: { type: "output", alsoCommand: "^wc +-l +scroll\\.txt( |$)", pattern: "^wc +-l +scroll\\.txt\\n *20 " },
        teach: {
          cmd: "wc -l",
          cmdZh: "数行数",
          what: "wc（word count）统计文本；-l 选项只数行数。",
          syntax: "wc -l 文件名",
          example: "wc -l scroll.txt",
          exampleOut: "20 scroll.txt",
          tip: "wc -l 后面可以跟多个文件，一次统计一批。",
        },
        hints: [
          "wc = word count；-l 表示数行数",
          "试试：wc -l scroll.txt",
          "在终端输入：wc -l scroll.txt",
        ],
      },
      {
        id: "t4",
        desc: "用 cat scroll.txt 通读全卷（确认最后一行是 line20）",
        judge: { type: "output", alsoCommand: "^cat +scroll\\.txt( |$)", pattern: "line20" },
        teach: {
          cmd: "cat",
          cmdZh: "通读全卷",
          what: "cat 把整个文件打印出来——卷轴不长，值得完整读一遍。",
          syntax: "cat 文件名",
          example: "cat scroll.txt",
          exampleOut: "line1 ... line20",
          tip: "文件太大就别用 cat 了，head/tail 分段看才是正道。",
        },
        hints: [
          "cat 打印整个文件内容",
          "试试：cat scroll.txt",
          "在终端输入：cat scroll.txt",
        ],
      },
    ],
  },
  {
    id: "2-6",
    chapter: 2,
    icon: "🐉",
    title: "迷宫之主（Boss）",
    subtitle: "限时综合挑战 · 逃出迷宫",
    timeLimit: 300,
    xp: 150,
    coins: 60,
    starRules: { two: { maxSteps: 10 }, three: { maxSteps: 7 } },
    story: [
      "迷宫之主现身：「想出去？完成我的六个考验：开路、搬运、复制、清理、搜索、清点！」",
      "废墟里藏着谜语 riddle.txt 和垃圾 old.txt，出口 exit 要靠你自己建造。",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/boss-maze/ruins", "cd /mnt/adv/boss-maze", "echo 'SECRET' > ruins/riddle.txt", "touch ruins/old.txt"],
    errorPatterns: [],
    tasks: [
      {
        id: "t1",
        desc: "用 mkdir exit 建造出口",
        judge: { type: "file", path: "adv/boss-maze/exit", alsoCommand: "^mkdir +exit( |$)" },
        teach: {
          cmd: "mkdir exit",
          cmdZh: "开路",
          what: "创建出口目录 exit。",
          syntax: "mkdir exit",
          example: "mkdir exit",
          exampleOut: "（没有输出 = 成功）",
          tip: "回忆：mkdir = make directory。",
        },
        hints: ["mkdir 创建目录", "试试：mkdir exit", "在终端输入：mkdir exit"],
      },
      {
        id: "t2",
        desc: "用 mv 把谜语搬进出口 mv ruins/riddle.txt exit/",
        judge: { type: "file", path: "adv/boss-maze/exit/riddle.txt", alsoCommand: "^mv +ruins/riddle\\.txt +exit/?( |$)" },
        teach: {
          cmd: "mv ruins/riddle.txt exit/",
          cmdZh: "搬运",
          what: "把废墟里的谜语文件搬进出口目录。",
          syntax: "mv 源 目录/",
          example: "mv ruins/riddle.txt exit/",
          exampleOut: "（没有输出 = 成功）",
          tip: "mv 到「目录/」= 搬进去。",
        },
        hints: ["mv 文件 目标目录", "试试：mv ruins/riddle.txt exit/", "在终端输入：mv ruins/riddle.txt exit/"],
      },
      {
        id: "t3",
        desc: "用 cp 复制一份谜语 exit/riddle.txt → exit/riddle_copy.txt",
        judge: { type: "file", path: "adv/boss-maze/exit/riddle_copy.txt", contains: "SECRET", alsoCommand: "^cp +exit/riddle\\.txt +exit/riddle_copy\\.txt( |$)" },
        teach: {
          cmd: "cp exit/riddle.txt exit/riddle_copy.txt",
          cmdZh: "复制",
          what: "复制谜语文件，留一个副本。",
          syntax: "cp 源 新文件",
          example: "cp exit/riddle.txt exit/riddle_copy.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "副本内容必须和原件一致（含 SECRET）。",
        },
        hints: ["cp 源文件 新文件", "试试：cp exit/riddle.txt exit/riddle_copy.txt", "在终端输入：cp exit/riddle.txt exit/riddle_copy.txt"],
      },
      {
        id: "t4",
        desc: "用 rm 清理废墟里的垃圾 ruins/old.txt",
        judge: { type: "file", path: "adv/boss-maze/ruins/old.txt", absent: true, alsoCommand: "^rm +ruins/old\\.txt( |$)" },
        teach: {
          cmd: "rm ruins/old.txt",
          cmdZh: "清理",
          what: "删除废墟里的旧文件。",
          syntax: "rm 路径/文件名",
          example: "rm ruins/old.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "rm 没有回收站，看准再删。",
        },
        hints: ["rm 删除文件", "试试：rm ruins/old.txt", "在终端输入：rm ruins/old.txt"],
      },
      {
        id: "t5",
        desc: "用 find exit -name \"*.txt\" 搜索出口里的文件",
        judge: { type: "output", alsoCommand: "^find +exit +-name +[\"']?\\*\\.txt[\"']?( |$)", pattern: "riddle" },
        teach: {
          cmd: "find exit -name \"*.txt\"",
          cmdZh: "搜索",
          what: "在出口目录递归搜索所有 txt 文件。",
          syntax: "find 目录 -name \"*.txt\"",
          example: "find exit -name \"*.txt\"",
          exampleOut: "exit/riddle.txt\nexit/riddle_copy.txt",
          tip: "-name 后面的模式加引号，防止 shell 提前展开通配符。",
        },
        hints: ["find 目录 -name 模式", "试试：find exit -name \"*.txt\"", "在终端输入：find exit -name \"*.txt\""],
      },
      {
        id: "t6",
        desc: "用 wc -l exit/riddle.txt 清点谜语行数",
        judge: { type: "output", alsoCommand: "^wc +-l +exit/riddle\\.txt( |$)", pattern: "^wc +-l +exit/riddle\\.txt\\n *[0-9]+ " },
        teach: {
          cmd: "wc -l exit/riddle.txt",
          cmdZh: "清点",
          what: "统计谜语文件的行数，完成最后一项考验。",
          syntax: "wc -l 路径/文件名",
          example: "wc -l exit/riddle.txt",
          exampleOut: "1 exit/riddle.txt",
          tip: "谜语只有一行 SECRET，所以行数是 1。",
        },
        hints: ["wc -l 数行数", "试试：wc -l exit/riddle.txt", "在终端输入：wc -l exit/riddle.txt"],
      },
    ],
  },
  {
    id: "3-1",
    chapter: 3,
    icon: "👑",
    title: "我是管理员",
    subtitle: "id / whoami / /etc/passwd",
    timeLimit: null,
    xp: 60,
    coins: 25,
    starRules: { two: { maxSteps: 7 }, three: { maxSteps: 4 } },
    story: [
      "你来到权限要塞门口，卫兵拦路：「报上你的身份！」",
      "Tux 说：「用 id 看看你是谁——我打赌你就是传说中的 root，这台机器的管理员。」",
    ],
    setupCmds: ["cd /"],
    errorPatterns: [
      { pattern: "^sudo( |$)", message: "这个迷你世界没有 sudo——你本来就是 root（管理员），直接执行命令就行" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 id 查看你的身份信息",
        judge: { type: "output", alsoCommand: "^id( |$)", pattern: "uid=0" },
        teach: {
          cmd: "id",
          cmdZh: "身份信息",
          what: "id 打印当前用户的 UID、GID 和所属组。",
          syntax: "id",
          example: "id",
          exampleOut: "uid=0(root) gid=0(root)",
          tip: "uid=0 就是 root——Linux 的管理员账号，权限最大。",
        },
        hints: ["id 显示用户身份信息", "输入 id 回车", "在终端输入：id"],
      },
      {
        id: "t2",
        desc: "用 whoami 看看你的用户名",
        judge: { type: "output", alsoCommand: "^whoami( |$)", pattern: "root" },
        teach: {
          cmd: "whoami",
          cmdZh: "用户名",
          what: "whoami 打印当前用户名——复习第一章的老朋友。",
          syntax: "whoami",
          example: "whoami",
          exampleOut: "root",
          tip: "root 是 Linux 的超级管理员，能改这台机器上的一切。",
        },
        hints: ["whoami 显示当前用户名", "输入 whoami 回车", "在终端输入：whoami"],
      },
      {
        id: "t3",
        desc: "用 cat /etc/passwd 查看这台机器的用户名单",
        judge: { type: "output", alsoCommand: "^cat +/etc/passwd( |$)", pattern: "root:x:0:0" },
        teach: {
          cmd: "cat /etc/passwd",
          cmdZh: "用户名单",
          what: "/etc/passwd 记录所有用户账号，每行一个用户。",
          syntax: "cat /etc/passwd",
          example: "cat /etc/passwd",
          exampleOut: "root:x:0:0:root:/root:/bin/sh",
          tip: "格式：用户名:密码占位:UID:GID:描述:家目录:shell。x 表示密码存在别处。",
        },
        hints: ["用户名单在 /etc/passwd 文件里", "试试：cat /etc/passwd", "在终端输入：cat /etc/passwd"],
      },
    ],
  },
  {
    id: "3-2",
    chapter: 3,
    icon: "🚪",
    title: "守护之门",
    subtitle: "ls -l 与 chmod",
    timeLimit: null,
    xp: 70,
    coins: 30,
    starRules: { two: { maxSteps: 10 }, three: { maxSteps: 7 } },
    story: [
      "要塞里有两扇门：open.txt 是普通文件，run.sh 是待执行的命令脚本。",
      "Tux 说：「用 ls -l 读权限，用 chmod 改权限——先锁门，再开门。」",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/perms", "cd /mnt/adv/perms", "touch open.txt", "echo 'echo hello' > run.sh"],
    errorPatterns: [],
    tasks: [
      {
        id: "t1",
        desc: "用 ls -l open.txt 查看它的权限",
        judge: { type: "output", alsoCommand: "^ls +-l +open\\.txt( |$)", pattern: "-rw-r--r--.*open\\.txt" },
        teach: {
          cmd: "ls -l",
          cmdZh: "读权限",
          what: "ls -l 每行开头的 10 个字符就是权限：-rw-r--r--。",
          syntax: "ls -l 文件名",
          example: "ls -l open.txt",
          exampleOut: "-rw-r--r-- 1 root root 0 Sep 25 12:00 open.txt",
          tip: "第 1 位是类型（- 文件 d 目录）；后 9 位分成三组：属主/属组/其他人，r=读 w=写 x=执行。",
        },
        hints: ["ls -l 显示文件详情和权限", "试试：ls -l open.txt", "在终端输入：ls -l open.txt"],
      },
      {
        id: "t2",
        desc: "用 chmod 600 open.txt 锁上这扇门（只有你能读写）",
        judge: { type: "command", pattern: "^chmod +600 +open\\.txt( |$)" },
        teach: {
          cmd: "chmod 600",
          cmdZh: "改权限",
          what: "chmod（change mode）修改权限。600 = 属主可读可写(6)，属组和其他人无权(0)。",
          syntax: "chmod 数字 文件名",
          example: "chmod 600 open.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "数字速记：r=4 w=2 x=1。6=4+2（读+写），7=4+2+1（全部）。",
        },
        hints: ["chmod 数字 文件名；600=属主读写", "试试：chmod 600 open.txt", "在终端输入：chmod 600 open.txt"],
      },
      {
        id: "t3",
        desc: "再用 ls -l open.txt 确认权限变成 -rw-------",
        judge: { type: "output", alsoCommand: "^ls +-l +open\\.txt( |$)", pattern: "-rw-------.*open\\.txt" },
        teach: {
          cmd: "ls -l 复查",
          cmdZh: "验证权限",
          what: "改完权限后，用 ls -l 复查——看到 -rw------- 就说明锁上了。",
          syntax: "ls -l 文件名",
          example: "ls -l open.txt",
          exampleOut: "-rw------- 1 root root 0 Sep 25 12:00 open.txt",
          tip: "改权限后立刻复查，是安全运维的好习惯。",
        },
        hints: ["再跑一次 ls -l open.txt", "看开头是不是 -rw-------", "在终端输入：ls -l open.txt"],
      },
      {
        id: "t4",
        desc: "用 chmod +x run.sh 给脚本加上执行权限",
        judge: { type: "command", pattern: "^chmod +\\+x +run\\.sh( |$)" },
        teach: {
          cmd: "chmod +x",
          cmdZh: "加执行权",
          what: "+x 是符号模式：给文件加上执行（x）权限，保留其他权限不变。",
          syntax: "chmod +x 文件名",
          example: "chmod +x run.sh",
          exampleOut: "（没有输出 = 成功）",
          tip: "脚本要能运行，必须有 x 权限——这就是「开门」的一步。",
        },
        hints: ["+x 表示加上执行权限", "试试：chmod +x run.sh", "在终端输入：chmod +x run.sh"],
      },
      {
        id: "t5",
        desc: "用 ./run.sh 运行脚本，听到它说 hello",
        judge: { type: "output", alsoCommand: "^\\./run\\.sh( |$)", pattern: "hello" },
        teach: {
          cmd: "./run.sh",
          cmdZh: "运行脚本",
          what: "./run.sh 表示「运行当前目录下的 run.sh」——只有加了 x 权限才能这样执行。",
          syntax: "./脚本名",
          example: "./run.sh",
          exampleOut: "hello",
          tip: "如果没加执行权限，./run.sh 会报 Permission denied——这正是 chmod +x 的意义。",
        },
        hints: ["./ 表示当前目录下的文件", "试试：./run.sh", "在终端输入：./run.sh"],
      },
    ],
  },
  {
    id: "3-3",
    chapter: 3,
    icon: "🏷️",
    title: "归属之争",
    subtitle: "chown 与 chgrp",
    timeLimit: null,
    xp: 70,
    coins: 30,
    starRules: { two: { maxSteps: 9 }, three: { maxSteps: 6 } },
    story: [
      "仓库里有个神秘文件 mystery.txt，主人是 root。",
      "Tux 说：「把它的主人交给 nobody（系统里的客人账号），组交给 audio——用 chown 和 chgrp。」",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/own", "cd /mnt/adv/own", "touch mystery.txt"],
    errorPatterns: [
      { pattern: "^chown +mystery( |$)", message: "顺序是：chown 新主人 文件" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 ls -l mystery.txt 查看当前归属",
        judge: { type: "output", alsoCommand: "^ls +-l +mystery\\.txt( |$)", pattern: "-rw-r--r--.*root +root.*mystery\\.txt" },
        teach: {
          cmd: "ls -l 看归属",
          cmdZh: "主人与组",
          what: "ls -l 的第 3、4 列就是文件的属主和属组——现在都是 root。",
          syntax: "ls -l 文件名",
          example: "ls -l mystery.txt",
          exampleOut: "-rw-r--r-- 1 root root 0 Sep 25 12:00 mystery.txt",
          tip: "权限三组（rwx）正是针对「属主 / 属组 / 其他人」三种身份。",
        },
        hints: ["ls -l 显示属主和属组", "试试：ls -l mystery.txt", "在终端输入：ls -l mystery.txt"],
      },
      {
        id: "t2",
        desc: "用 chown nobody mystery.txt 把主人交给 nobody",
        judge: { type: "command", pattern: "^chown +nobody +mystery\\.txt( |$)" },
        teach: {
          cmd: "chown",
          cmdZh: "换主人",
          what: "chown（change owner）修改文件属主：chown 新主人 文件。",
          syntax: "chown 用户名 文件名",
          example: "chown nobody mystery.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "nobody 是系统里的「客人」账号（uid=65534），常被用来表示最小权限。",
        },
        hints: ["chown 新主人 文件", "试试：chown nobody mystery.txt", "在终端输入：chown nobody mystery.txt"],
      },
      {
        id: "t3",
        desc: "用 ls -l 确认主人变成 nobody（组还是 root）",
        judge: { type: "output", alsoCommand: "^ls +-l +mystery\\.txt( |$)", pattern: "-rw-r--r--.*nobody +root.*mystery\\.txt" },
        teach: {
          cmd: "ls -l 复查",
          cmdZh: "验证归属",
          what: "复查：第 3 列变成 nobody，第 4 列还是 root——chown 只换主人不动组。",
          syntax: "ls -l 文件名",
          example: "ls -l mystery.txt",
          exampleOut: "-rw-r--r-- 1 nobody root 0 Sep 25 12:00 mystery.txt",
          tip: "改完立刻复查，确认归属真的变了。",
        },
        hints: ["再跑一次 ls -l mystery.txt", "看第 3 列是不是 nobody", "在终端输入：ls -l mystery.txt"],
      },
      {
        id: "t4",
        desc: "用 chgrp audio mystery.txt 把组换成 audio",
        judge: { type: "command", pattern: "^chgrp +audio +mystery\\.txt( |$)" },
        teach: {
          cmd: "chgrp",
          cmdZh: "换组",
          what: "chgrp（change group）修改文件的属组：chgrp 新组 文件。",
          syntax: "chgrp 组名 文件名",
          example: "chgrp audio mystery.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "系统里有哪些组？cat /etc/group 就能看到（audio 是声音设备组）。",
        },
        hints: ["chgrp 新组 文件", "试试：chgrp audio mystery.txt", "在终端输入：chgrp audio mystery.txt"],
      },
      {
        id: "t5",
        desc: "用 ls -l 确认组也变成了 audio",
        judge: { type: "output", alsoCommand: "^ls +-l +mystery\\.txt( |$)", pattern: "-rw-r--r--.*nobody +audio.*mystery\\.txt" },
        teach: {
          cmd: "ls -l 终检",
          cmdZh: "最终归属",
          what: "终检：主人 nobody、组 audio——归属交接完成！",
          syntax: "ls -l 文件名",
          example: "ls -l mystery.txt",
          exampleOut: "-rw-r--r-- 1 nobody audio 0 Sep 25 12:00 mystery.txt",
          tip: "chown 换主人、chgrp 换组，两个命令各管一样。",
        },
        hints: ["最后一次 ls -l mystery.txt", "看第 4 列是不是 audio", "在终端输入：ls -l mystery.txt"],
      },
    ],
  },
  {
    id: "3-4",
    chapter: 3,
    icon: "🛡️",
    title: "招兵买马",
    subtitle: "adduser / addgroup / id",
    timeLimit: null,
    xp: 70,
    coins: 30,
    starRules: { two: { maxSteps: 9 }, three: { maxSteps: 6 } },
    story: [
      "要塞要扩充兵力！Tux 递给你征兵手册：",
      "「先创建骑士团 knights，再创建勇士 hero 并直接编入骑士团，最后验明身份、核对名册。」",
    ],
    setupCmds: ["cd /"],
    errorPatterns: [
      { pattern: "^useradd( |$)|^groupadd( |$)", message: "这个迷你世界用 BusyBox 的 adduser / addgroup（没有 useradd/groupadd）" },
      { pattern: "^adduser +hero +knights( |$)|^addgroup +hero +knights( |$)", message: "这台 BusyBox 不支持事后编组——创建用户时用 -G 指定组：adduser -D -H -G knights hero" },
      { pattern: "^adduser +-D +-H +hero( |$)", message: "勇士还没编入骑士团：加上 -G knights（记得先创建组：addgroup knights）" },
    ],
    tasks: [
      {
        id: "t1",
        desc: "用 addgroup knights 创建骑士团",
        judge: { type: "command", pattern: "^addgroup +knights( |$)" },
        teach: {
          cmd: "addgroup",
          cmdZh: "创建组",
          what: "addgroup 创建新组，登记在 /etc/group 里。",
          syntax: "addgroup 组名",
          example: "addgroup knights",
          exampleOut: "（没有输出 = 成功）",
          tip: "组用来批量管理权限：把文件属组设为 knights，全团都能访问。",
        },
        hints: ["addgroup 组名", "试试：addgroup knights", "在终端输入：addgroup knights"],
      },
      {
        id: "t2",
        desc: "用 adduser -D -H -G knights hero 创建勇士并编入骑士团",
        judge: { type: "command", pattern: "^adduser +-D +-H +-G +knights +hero( |$)" },
        teach: {
          cmd: "adduser -D -H -G knights hero",
          cmdZh: "创建用户并编组",
          what: "adduser 创建新用户：-D 不设密码（无交互）、-H 不建家目录、-G 组名 指定用户所属组。",
          syntax: "adduser -D -H -G 组名 用户名",
          example: "adduser -D -H -G knights hero",
          exampleOut: "（没有输出 = 成功）",
          tip: "这台 BusyBox 只能在创建时用 -G 指定组，事后改不了——所以一步到位。",
        },
        hints: ["-G 组名 在创建时指定组", "试试：adduser -D -H -G knights hero", "在终端输入：adduser -D -H -G knights hero"],
      },
      {
        id: "t3",
        desc: "用 cat /etc/passwd 确认 hero 已登记",
        judge: { type: "output", alsoCommand: "^cat +/etc/passwd( |$)", pattern: "hero:x:" },
        teach: {
          cmd: "cat /etc/passwd",
          cmdZh: "核对名册",
          what: "创建用户后，/etc/passwd 末尾会出现 hero 的记录。",
          syntax: "cat /etc/passwd",
          example: "cat /etc/passwd",
          exampleOut: "hero:x:1000:1000:Linux User,,,:/home/hero:/bin/sh",
          tip: "新用户通常在文件最后几行，tail /etc/passwd 查看更快。",
        },
        hints: ["用户名单在 /etc/passwd", "试试：cat /etc/passwd（找 hero 那一行）", "在终端输入：cat /etc/passwd"],
      },
      {
        id: "t4",
        desc: "用 id hero 验明勇士身份（应包含 knights）",
        judge: { type: "output", alsoCommand: "^id +hero( |$)", pattern: "knights" },
        teach: {
          cmd: "id 用户名",
          cmdZh: "验明身份",
          what: "id 加用户名查看指定用户的身份——gid 里应该出现 knights。",
          syntax: "id 用户名",
          example: "id hero",
          exampleOut: "uid=1000(hero) gid=1000(knights) groups=1000(knights)",
          tip: "gid=1000(knights) 说明 hero 的主组就是骑士团——征兵完成！",
        },
        hints: ["id 用户名 查看指定用户", "试试：id hero", "在终端输入：id hero"],
      },
      {
        id: "t5",
        desc: "用 cat /etc/group 查看组名册（找 knights）",
        judge: { type: "output", alsoCommand: "^cat +/etc/group( |$)", pattern: "knights:x:" },
        teach: {
          cmd: "cat /etc/group",
          cmdZh: "组名册",
          what: "/etc/group 记录所有组，每行一个：组名:密码占位:GID:成员列表。",
          syntax: "cat /etc/group",
          example: "cat /etc/group",
          exampleOut: "knights:x:1000:",
          tip: "组的「身份证」在这里；用户属于哪个组，则记录在 /etc/passwd 的 GID 字段里。",
        },
        hints: ["组名册在 /etc/group", "试试：cat /etc/group（找 knights 那一行）", "在终端输入：cat /etc/group"],
      },
    ],
  },
  {
    id: "3-5",
    chapter: 3,
    icon: "🏰",
    title: "要塞防御战（Boss）",
    subtitle: "限时综合挑战 · 守护要塞",
    timeLimit: 300,
    xp: 150,
    coins: 60,
    starRules: { two: { maxSteps: 10 }, three: { maxSteps: 7 } },
    story: [
      "敌军来袭！指挥官下令：「把军旗 banner.txt 藏进金库 vault，锁上金库，把军旗交给客人 nobody 保管，最后验收！」",
      "限时 5 分钟——用你学过的文件与权限技能守住要塞。",
    ],
    setupCmds: ["cd /", "mkdir -p /mnt/adv/fort", "cd /mnt/adv/fort", "echo 'FLAG: 要塞守住了' > banner.txt"],
    errorPatterns: [],
    tasks: [
      {
        id: "t1",
        desc: "用 mkdir vault 建造金库",
        judge: { type: "file", path: "adv/fort/vault", alsoCommand: "^mkdir +vault( |$)" },
        teach: {
          cmd: "mkdir vault",
          cmdZh: "建金库",
          what: "创建金库目录 vault。",
          syntax: "mkdir vault",
          example: "mkdir vault",
          exampleOut: "（没有输出 = 成功）",
          tip: "回忆：mkdir = make directory。",
        },
        hints: ["mkdir 创建目录", "试试：mkdir vault", "在终端输入：mkdir vault"],
      },
      {
        id: "t2",
        desc: "用 mv banner.txt vault/ 把军旗藏进金库",
        judge: { type: "file", path: "adv/fort/vault/banner.txt", alsoCommand: "^mv +banner\\.txt +vault/?( |$)" },
        teach: {
          cmd: "mv banner.txt vault/",
          cmdZh: "藏军旗",
          what: "把军旗文件移进金库目录。",
          syntax: "mv 文件 目录/",
          example: "mv banner.txt vault/",
          exampleOut: "（没有输出 = 成功）",
          tip: "mv 到「目录/」= 搬进去。",
        },
        hints: ["mv 文件 目标目录", "试试：mv banner.txt vault/", "在终端输入：mv banner.txt vault/"],
      },
      {
        id: "t3",
        desc: "用 chmod 700 vault 锁上金库（只有你能进出）",
        judge: { type: "command", pattern: "^chmod +700 +vault( |$)" },
        teach: {
          cmd: "chmod 700",
          cmdZh: "锁金库",
          what: "700 = 属主可读可写可执行(7)，其他身份无任何权限(0)——金库只有你能进出。",
          syntax: "chmod 700 目录名",
          example: "chmod 700 vault",
          exampleOut: "（没有输出 = 成功）",
          tip: "目录的 x 权限 = 能进入该目录；700 意味着别人连门都进不去。",
        },
        hints: ["chmod 数字 目录名；700=属主全部", "试试：chmod 700 vault", "在终端输入：chmod 700 vault"],
      },
      {
        id: "t4",
        desc: "用 chown nobody vault/banner.txt 把军旗交给客人保管",
        judge: { type: "command", pattern: "^chown +nobody +vault/banner\\.txt( |$)" },
        teach: {
          cmd: "chown nobody",
          cmdZh: "交军旗",
          what: "把军旗文件的属主改为 nobody——最小权限原则：客人只管军旗，管不了金库。",
          syntax: "chown 用户名 路径/文件",
          example: "chown nobody vault/banner.txt",
          exampleOut: "（没有输出 = 成功）",
          tip: "root 可以 chown 任何文件；普通用户不行。",
        },
        hints: ["chown 新主人 文件", "试试：chown nobody vault/banner.txt", "在终端输入：chown nobody vault/banner.txt"],
      },
      {
        id: "t5",
        desc: "用 ls -ld vault 验收金库权限（应为 drwx------）",
        judge: { type: "output", alsoCommand: "^ls +-ld +vault( |$)", pattern: "drwx------.*vault" },
        teach: {
          cmd: "ls -ld",
          cmdZh: "验收目录权限",
          what: "ls -ld 显示目录自身的权限（不加 -d 会列出目录内容）。",
          syntax: "ls -ld 目录名",
          example: "ls -ld vault",
          exampleOut: "drwx------ 2 root root 4096 Sep 25 12:00 vault",
          tip: "d 开头表示目录；drwx------ 正是 700 权限——金库锁好了。",
        },
        hints: ["ls -ld 显示目录自身权限", "试试：ls -ld vault", "在终端输入：ls -ld vault"],
      },
      {
        id: "t6",
        desc: "用 cat vault/banner.txt 验收军旗（看到 FLAG 即胜利）",
        judge: { type: "output", alsoCommand: "^cat +vault/banner\\.txt( |$)", pattern: "FLAG:" },
        teach: {
          cmd: "cat vault/banner.txt",
          cmdZh: "验收军旗",
          what: "读取军旗内容——看到 FLAG 就是防御成功。",
          syntax: "cat 路径/文件名",
          example: "cat vault/banner.txt",
          exampleOut: "FLAG: 要塞守住了",
          tip: "root 不受 700 限制，随时可以验收。",
        },
        hints: ["cat 查看文件内容", "试试：cat vault/banner.txt", "在终端输入：cat vault/banner.txt"],
      },
    ],
  },
];

// 公共错误模式并入每一关（具体关卡的模式优先匹配）
for (const lv of LEVELS) {
  lv.errorPatterns = [...(lv.errorPatterns || []), ...COMMON_ERRORS];
}
